### ISSUE TITLE
API igredient amount returns 0

### ISSUE THREAD

**Issue by tomatosauc** [porisius/FicsitRemoteMonitoring#87]
I am rewriting the [Ficsit Remote Monitoring Dashboard](https://ficsit-rmd.vercel.app/), because some features were not working properly or at all after some mod update, and currently I am debugging the mod API returning 0 as the amount of any ingredient in any machine. The product amount is okay and consumption amount as well it's just the inventory of the inputs of the machine. Any help would be greatly appreciated.

**Comment by porisius** [comment]
Could you verify again the latest test build please?

I did some bug squashing. While I don't think I addressed your issue specifically, I would rather start from a known point than wonder.

https://drive.google.com/drive/folders/1jjzIE8eczElSeoCFCg0weJeJw7fALpnc?usp=sharing

If this doesn't help, please let me know what endpoint you are using and the json output.

**Comment by tomatosauc** [comment]
Tried installing the test build... It did not fix the amount, but it did fix getFactory endpoint, which wasn't reachable before. 
Here is the returned json from /getParticle endpoint from my testing world: `[
    {
        "Name": "Particle Accelerator",
        "ClassName": "Build_HadronCollider_C",
        "location": {
            "x": 81915.109375,
            "y": 105237.25,
            "z": 10241.697265625,
            "rotation": 89.09369221083301
        },
        "Recipe": "Plutonium Pellet",
        "RecipeClassName": "Recipe_Plutonium_C",
        "production": [
            {
                "Name": "Plutonium Pellet",
                "ClassName": "Desc_PlutoniumPellet_C",
                "Amount": 0,
                "CurrentProd": 0,
                "MaxProd": 30,
                "ProdPercent": 0
            }
        ],
        "ingredients": [
            {
                "Name": "Non-Fissile Uranium",
                "ClassName": "Desc_NonFissibleUranium_C",
                "Amount": 0,
                "CurrentConsumed": 0,
                "MaxConsumed": 100,
                "ConsPercent": 0
            },
            {
                "Name": "Uranium Waste",
                "ClassName": "Desc_NuclearWaste_C",
                "Amount": 0,
                "CurrentConsumed": 0,
                "MaxConsumed": 25,
                "ConsPercent": 0
            }
        ],
        "ManuSpeed": 100,
        "IsConfigured": true,
        "IsProducing": false,
        "IsPaused": false,
        "PowerInfo": [
            {
                "CircuitGroupID": 1,
                "CircuitID": 17,
                "PowerConsumed": 0.10000000149011612
            }
        ],
        "CircuitID": 17,
        "features": {
            "properties": {
                "name": "Particle Accelerator",
                "type": "Particle Accelerator"
            },
            "geometry": {
                "coordinates": {
                    "x": 81915.109375,
                    "y": 105237.25,
                    "z": 10241.697265625
                },
                "type": "Point"
            }
        }
    },
    {
        "Name": "Particle Accelerator",
        "ClassName": "Build_HadronCollider_C",
        "location": {
            "x": 153724.171875,
            "y": 76683.8984375,
            "z": 10043.833984375,
            "rotation": 89.29289321881345
        },
        "Recipe": "Diamonds",
        "RecipeClassName": "Recipe_Diamond_C",
        "production": [
            {
                "Name": "Diamonds",
                "ClassName": "Desc_Diamond_C",
                "Amount": 0,
                "CurrentProd": 30,
                "MaxProd": 30,
                "ProdPercent": 100
            }
        ],
        "ingredients": [
            {
                "Name": "Coal",
                "ClassName": "Desc_Coal_C",
                "Amount": 0,
                "CurrentConsumed": 600,
                "MaxConsumed": 600,
                "ConsPercent": 100
            }
        ],
        "ManuSpeed": 100,
        "IsConfigured": true,
        "IsProducing": true,
        "IsPaused": false,
        "PowerInfo": [
            {
                "CircuitGroupID": 5,
                "CircuitID": 8,
                "PowerConsumed": 509.8099060058594
            }
        ],
        "CircuitID": 8,
        "features": {
            "properties": {
                "name": "Particle Accelerator",
                "type": "Particle Accelerator"
            },
            "geometry": {
                "coordinates": {
                    "x": 153724.171875,
                    "y": 76683.8984375,
                    "z": 10043.833984375
                },
                "type": "Point"
            }
        }
    },
    {
        "Name": "Particle Accelerator",
        "ClassName": "Build_HadronCollider_C",
        "location": {
            "x": 152683.546875,
            "y": 58161.8046875,
            "z": 9499.55859375,
            "rotation": 90.96592582574675
        },
        "Recipe": "Alternate: Dark Matter Crystallization",
        "RecipeClassName": "Recipe_Alternate_DarkMatter_Crystallization_C",
        "production": [
            {
                "Name": "Dark Matter Crystal",
                "ClassName": "Desc_DarkMatter_C",
                "Amount": 200,
                "CurrentProd": 0,
                "MaxProd": 15,
                "ProdPercent": 0
            }
        ],
        "ingredients": [
            {
                "Name": "Dark Matter Residue",
                "ClassName": "Desc_DarkEnergy_C",
                "Amount": 0,
                "CurrentConsumed": 0,
                "MaxConsumed": 150,
                "ConsPercent": 0
            }
        ],
        "ManuSpeed": 100,
        "IsConfigured": true,
        "IsProducing": false,
        "IsPaused": false,
        "PowerInfo": [
            {
                "CircuitGroupID": 5,
                "CircuitID": 8,
                "PowerConsumed": 0.10000000149011612
            }
        ],
        "CircuitID": 8,
        "features": {
            "properties": {
                "name": "Particle Accelerator",
                "type": "Particle Accelerator"
            },
            "geometry": {
                "coordinates": {
                    "x": 152683.546875,
                    "y": 58161.8046875,
                    "z": 9499.55859375
                },
                "type": "Point"
            }
        }
    }
]`

**Comment by porisius** [comment]
Well, that's about 5 pieces to have to vet now...

Would you be okay DM'ing me your save either here, or through Discord, please? I will have to tinker a little bit, and don't wish to disturb you with constant "can you try this" requests.

**Comment by porisius** [comment]
Was grabbing from wrong inventory
https://github.com/porisius/FicsitRemoteMonitoring/commit/e21737ab5521c15274e3d07b620183660ece7fc3

**Comment by porisius** [comment]
Fixed in 1.1.0
